import re


s = 'TCATTTGACTTAGCCATCATCATGGAACGTCGCTACTAATAAGTAACGTGTGCATTATGGCACGAAAAGAGACGTGAGAAAGTGCCTATGGAATCATACTTTGACCGAGCATGCCCCTCGAACTAATTGCTTTGGGCCCTTGGTTACGTATGCGAAAGAGACGATTGAAGTGGTAGCTTATAGGAAGAGATGCCGAGAGAGAGGGCTGAGCCTCAGTAACCCAGAATTATCACACGCGCTAATATGGAAAGCTCTATCATTTCCGCCGGTCGAGAGGCTACGCCATTGGCGTACGAACGATAA'

find ='ATG'
find_end = '(TAA|TAG|TGA)'
result =  re.split(find,s)
# result2 = re.split(find_end, s)
print(result)
for i in result:
    i = "".join(('ATG',i))
    for k in range(len(i)):
        print(i[k:k+3])
        if i[k:k+3] == 'TAA'or i[k:k+3] == 'TAG' or i[k:k+3] == 'TGA':
            print(i[0:k+3])
